name: Manual release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  release:
    runs-on: windows-2019
    timeout-minutes: 5
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: |
        nuget sources add -Name "nhydockGithub" -Source "https://nuget.pkg.github.com/nhydock/index.json" -username ${{ secrets.PACKAGES_USER }} -password ${{ secrets.PACKAGES_TOKEN }}
        nuget restore BepInEx.DARLING.sln
 
    - name: Build and Publish
      run: msbuild BepInEx.DARLING.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:Version=${{ github.event.inputs.version }}
    
    - name: Zip artifacts
      run: |
        powershell Compress-Archive -Path bin/BepInEx -DestinationPath DARLING.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: Release v${{ github.event.inputs.version }}
        body: write the changelog you lazy fuk
        draft: true
        prerelease: false
        
    - name: Upload Koikatsu Plugin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: DARLING.zip
        asset_name: DARLING_${{ github.event.inputs.version }}.zip
        asset_content_type: application/zip
